"""Simulation Diagnostic & Controller Evaluation Suite — Public Showcase.

Demonstrates the architecture of a multi-scenario controller evaluation
pipeline using synthetic showcase data.

This public implementation is intentionally incomplete. Production-specific
physics models, estimator implementations, controller tuning, feature
engineering, trained artifacts, hardware mappings, telemetry, and evaluation
data are not included.

All numerical results generated by this showcase are synthetic and must not
be interpreted as production performance measurements.
"""

import logging
import sys
from pathlib import Path
from typing import Any

# --- DYNAMIC PROJECT ROOT RESOLUTION ---
PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

import matplotlib.pyplot as plt
import pandas as pd

from src.simulation_engine import SimulationEngine

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
)

logger = logging.getLogger(__name__)

ACTUATOR_STATE_MAP: dict[str, int] = {"OFF": 0, "LOW": 1, "MED": 2, "HIGH": 3}

PUBLIC_SCENARIOS: dict[str, dict[str, Any]] = {
    "High Emission Scenario": {
        "scenario_title": "Synthetic High Load",
        "total_duration_min": 60.0,
        "activities": [
            {
                "activity_name": "High-Intensity Activity",
                "start_time_min": 5.0,
                "duration_min": 15.0,
                "intensity": "high",
            }
        ],
    },
    "Moderate Emission Scenario": {
        "scenario_title": "Synthetic Moderate Load",
        "total_duration_min": 60.0,
        "activities": [
            {
                "activity_name": "Moderate Activity",
                "start_time_min": 10.0,
                "duration_min": 25.0,
                "intensity": "medium",
            }
        ],
    },
    "Low Ambient Drift": {
        "scenario_title": "Synthetic Background",
        "total_duration_min": 60.0,
        "activities": [
            {
                "activity_name": "Background Activity",
                "start_time_min": 0.0,
                "duration_min": 60.0,
                "intensity": "low",
            }
        ],
    },
}


def run_and_plot_full_diagnostics(duration_min: float = 60.0) -> None:
    """Execute multi-scenario diagnostics and export report artifacts."""
    all_metrics: list[dict[str, Any]] = []
    num_scenarios = len(PUBLIC_SCENARIOS)

    # Updated grid layout to 3 columns
    fig, axes = plt.subplots(
        nrows=num_scenarios,
        ncols=3,
        figsize=(18, 4 * num_scenarios),
        sharex=True,
        squeeze=False,
    )
    fig.suptitle(
        f"Multi-Scenario Diagnostic Framework Evaluation across {num_scenarios} Scenarios",
        fontsize=14,
        fontweight="bold",
    )

    for i, (scenario_name, params) in enumerate(PUBLIC_SCENARIOS.items()):
        logger.info(
            "Simulating scenario %d/%d: %s...",
            i + 1,
            num_scenarios,
            scenario_name,
        )

        # Execute simulation via public interface
        res_pro = SimulationEngine.run_simulation(
            params, duration_min, mode="proactive"
        )
        res_rea = SimulationEngine.run_simulation(params, duration_min, mode="reactive")

        df_pro, df_rea = res_pro.telemetry, res_rea.telemetry
        t_series = df_pro["time_min"]

        # Defensive fallback series for optional channels
        zero_series = pd.Series(0.0, index=t_series.index)
        ref_series = pd.Series(0.80, index=t_series.index)

        all_metrics.extend(
            [
                {"Scenario": scenario_name, "Mode": "Proactive", **res_pro.metrics},
                {"Scenario": scenario_name, "Mode": "Reactive", **res_rea.metrics},
            ]
        )

        # ---------------------------------------------------------------------
        # Panel 1 (Col 0): Primary Air Quality Telemetry
        # ---------------------------------------------------------------------
        ax_aq = axes[i, 0]
        l1 = ax_aq.plot(
            t_series,
            df_pro["pm2_5"],
            color="crimson",
            linewidth=2,
            label="Proactive Stream",
        )
        l2 = ax_aq.plot(
            t_series,
            df_rea["pm2_5"],
            color="darkorange",
            linewidth=1.5,
            linestyle="--",
            label="Reactive Stream",
        )
        ax_aq.axhline(
            12.0,
            color="black",
            linestyle=":",
            alpha=0.5,
            label="Illustrative Reference Level",
        )
        ax_aq.set_ylabel("PM2.5 (a.u.)", color="crimson", fontweight="bold")

        ax_gas = ax_aq.twinx()
        l3 = ax_gas.plot(
            t_series,
            df_pro["co2"],
            color="forestgreen",
            linewidth=1.2,
            alpha=0.7,
            label="CO2 Telemetry",
        )
        l4 = ax_gas.plot(
            t_series,
            df_pro["voc"],
            color="gold",
            linewidth=1.2,
            alpha=0.7,
            label="VOC Telemetry",
        )
        ax_gas.set_ylabel("CO2 / VOC (a.u.)", color="forestgreen", fontweight="bold")

        lines_1 = l1 + l2 + l3 + l4
        ax_aq.legend(
            lines_1,
            [l.get_label() for l in lines_1],
            loc="upper right",
            fontsize=7,
        )
        ax_aq.set_title(
            f"{scenario_name} — Signal Dynamics",
            fontsize=10,
            loc="left",
            fontweight="bold",
        )
        ax_aq.grid(True, alpha=0.3)

        # ---------------------------------------------------------------------
        # Panel 2 (Col 1): Control States & State Estimator
        # ---------------------------------------------------------------------
        ax_ctrl = axes[i, 1]
        act_pro_num = df_pro["actuator_state"].map(ACTUATOR_STATE_MAP).fillna(0)
        act_rea_num = df_rea["actuator_state"].map(ACTUATOR_STATE_MAP).fillna(0)

        f1 = ax_ctrl.step(
            t_series,
            act_pro_num,
            color="black",
            linewidth=2,
            where="post",
            label="Proactive Actuation",
        )
        f2 = ax_ctrl.step(
            t_series,
            act_rea_num,
            color="dodgerblue",
            linewidth=1.5,
            linestyle="--",
            where="post",
            label="Reactive Actuation",
        )

        ax_ctrl.set_yticks([0, 1, 2, 3])
        ax_ctrl.set_yticklabels(["OFF", "LOW", "MED", "HIGH"])
        ax_ctrl.set_ylabel("Actuator Level", color="black", fontweight="bold")

        ax_est = ax_ctrl.twinx()
        c1 = ax_est.plot(
            t_series,
            df_pro.get("state_estimate", zero_series),
            color="magenta",
            linewidth=1.5,
            alpha=0.85,
            label="State Estimate",
        )
        ax_est.set_ylabel("State Magnitude (a.u.)", color="magenta", fontweight="bold")

        lines_2 = f1 + f2 + c1
        ax_ctrl.legend(
            lines_2,
            [l.get_label() for l in lines_2],
            loc="upper right",
            fontsize=7,
        )
        ax_ctrl.set_title(
            f"{scenario_name} — Actuation & State Estimation",
            fontsize=10,
            loc="left",
            fontweight="bold",
        )
        ax_ctrl.grid(True, alpha=0.3)

        # ---------------------------------------------------------------------
        # Panel 3 (Col 2): Event Probability & Control Gate Reference
        # ---------------------------------------------------------------------
        ax_ml = axes[i, 2]
        m1 = ax_ml.plot(
            t_series,
            df_pro.get("event_probability", zero_series),
            color="teal",
            linewidth=1.5,
            label="Event Probability",
        )
        l_thresh = ax_ml.step(
            t_series,
            df_pro.get("control_gate_reference", ref_series),
            color="darkslategrey",
            linestyle=":",
            linewidth=1.5,
            where="post",
            label="Gate Reference",
        )

        lines_3 = m1 + [l_thresh[0]]
        ax_ml.legend(
            lines_3,
            [l.get_label() for l in lines_3],
            loc="upper right",
            fontsize=7,
        )
        ax_ml.set_ylabel(
            "Probability / Reference Level", color="teal", fontweight="bold"
        )
        ax_ml.set_ylim(-0.05, 1.05)
        ax_ml.set_title(
            f"{scenario_name} — Event Detection & Gating",
            fontsize=10,
            loc="left",
            fontweight="bold",
        )
        ax_ml.grid(True, alpha=0.3)

    # Format bottom X-axes for 3 columns
    for col in range(3):
        axes[num_scenarios - 1, col].set_xlabel("Time (minutes)", fontweight="bold")

    plt.tight_layout(rect=(0, 0.02, 1, 0.97))

    # Save artifacts
    reports_dir = PROJECT_ROOT / "reports"
    reports_dir.mkdir(parents=True, exist_ok=True)

    output_png = reports_dir / "scenario_diagnostics_comparison.png"
    plt.savefig(output_png, dpi=300)
    logger.info("Exported plot artifact: %s", output_png)

    df_metrics = pd.DataFrame(all_metrics).set_index(["Scenario", "Mode"])
    output_csv = reports_dir / "scenario_diagnostics_metrics.csv"
    df_metrics.to_csv(output_csv)
    logger.info("Exported summary metrics table: %s", output_csv)


if __name__ == "__main__":
    run_and_plot_full_diagnostics(duration_min=60.0)
