"""
src/simulation_engine.py

Public simulation interface for the portfolio showcase.

The production implementation contains proprietary numerical models,
physics calibration, controller logic, and telemetry-generation methods.
Those components are intentionally not included in this public repository.

This module provides a lightweight synthetic implementation that preserves
the public interface used by the API and frontend without exposing
production IP.
"""

from dataclasses import dataclass
from typing import Any

import numpy as np
import pandas as pd


@dataclass
class SimulationResult:
    """
    Container for simulation outputs.

    Attributes
    ----------
    telemetry:
        Time-series telemetry generated by the showcase simulation.
    metrics:
        Summary metrics associated with the simulation run.
    plot_base64:
        Optional encoded diagnostic plot.
    """

    telemetry: pd.DataFrame
    metrics: dict[str, Any]
    plot_base64: str = ""

    def __getitem__(self, key: str) -> Any:
        """Allow dictionary-style access for compatibility."""
        return getattr(self, key)


class SimulationEngine:
    """
    Public simulation interface used by the showcase application.

    The public implementation intentionally contains no production
    physics equations, calibrated parameters, controller tuning,
    optimization logic, or proprietary telemetry-generation code.
    """

    @staticmethod
    def _build_showcase_telemetry(
        duration_min: float,
    ) -> pd.DataFrame:
        """
        Generate synthetic telemetry preserving the public schema.

        The values are placeholders for demonstration purposes and
        are not representative of production measurements.
        """
        duration_min = max(float(duration_min), 0.0)
        n_points = max(int(np.ceil(duration_min)) + 1, 1)

        time_min = np.linspace(
            0.0,
            duration_min,
            n_points,
        )

        return pd.DataFrame(
            {
                "time_min": time_min,
                "pm2_5": np.zeros(n_points),
                "co2": np.zeros(n_points),
                "voc": np.zeros(n_points),
                "event_probability": np.zeros(n_points),
                "actuator_state": ["OFF"] * n_points,
            }
        )

    @staticmethod
    def run_simulation(
        params: dict[str, Any],
        duration_min: float = 60.0,
        mode: str = "proactive",
    ) -> SimulationResult:
        """
        Execute a showcase simulation.

        Parameters
        ----------
        params:
            Validated, abstract scenario parameters.
            Production physical parameters are intentionally excluded
            from the public implementation.

        duration_min:
            Simulation timeline horizon in minutes.

        mode:
            Control strategy identifier, e.g. ``"proactive"`` or
            ``"reactive"``.

        Returns
        -------
        SimulationResult
            Synthetic telemetry, summary metrics, and an optional
            diagnostic plot placeholder.
        """
        normalized_mode = mode.strip().lower()

        if normalized_mode not in {"proactive", "reactive"}:
            raise ValueError("mode must be 'proactive' or 'reactive'")

        telemetry_df = SimulationEngine._build_showcase_telemetry(
            duration_min=duration_min
        )

        # Safely extract activities list from input params
        activities = params.get("activities", [])

        metrics = {
            "controller": normalized_mode.capitalize(),
            "simulation_type": "synthetic_showcase",
            "scenario_activities": len(activities),
            "peak_pm2_5": 0.0,
        }

        return SimulationResult(
            telemetry=telemetry_df,
            metrics=metrics,
            plot_base64="",
        )
